### ISSUE TITLE
works locally, but not over ssh

### ISSUE THREAD

**Issue by dougbevan** [mountassir/gmonitor#19]
Hello.

Great utility.  I'd like to hvae the ability to use this over SSH, but it returns the following error:

---------------------
ERROR: The control display is undefined; please run `nvidia-settings --help` for usage information.

No gpus to monitor, terminating.
-----------------

However, this works when I run on the same system locally.  Is there a way to patch it to work also via SSH?

**Comment by mountassir** [comment]
Hi, please use ` -s ` to your running command, more info in the main page of gmonitor.
