### ISSUE TITLE
Cannot use through ssh

### ISSUE THREAD

**Issue by maccopari** [mountassir/gmonitor#4]
No problem when launched on local terminal, but if I'm using my machine through ssh I get this error:

'''
Failed to connect to Mir: Failed to connect to se
rver socket: No such file or directory           
Unable to init server: Could not connect: Connect
ion refused                                      
                                                 
ERROR: The control display is undefined; please  
       run `nvidia-settings --help` for usage    
       information.                              
                                                 
No gpus to monitor, terminating.
'''

**Comment by lucberger** [comment]
With ssh, use this command : 

`gmonitor -s`
